maven_build:
    image:  maven:3-jdk-8
    script: mvn -B clean install deploy site-deploy -DfullBuild -s ci_settings.xml -P clean-dependencies,!sign-artifacts -Dmvnsiteuploader-pwd=$mvnsiteuploader_pwd
    only:
        - master

maven_release:
    image:  maven:3-jdk-8
    script: mvn -B clean release:prepare release:perform site-deploy -DfullBuild -s ci_settings.xml -P clean-dependencies,!sign-artifacts -Dmvnsiteuploader-pwd=$mvnsiteuploader_pwd
    only:
        - release
