maven_build:
    image:  maven:3-jdk-8
    script: mvn -X -e -B clean install deploy site -DfullBuild -s ci_settings.xml -P clean-dependencies,!sign-artifacts
    only:
        - master

maven_release:
    image:  maven:3-jdk-8
    script: mvn -B clean release:prepare release:perform site -DfullBuild -s ci_settings.xml -P clean-dependencies,!sign-artifacts
    only:
        - release
