################################################################################
# Development Filter Sample File											   #
#------------------------------------------------------------------------------#
#																			   #
# This file contains all properties, which are depends on the build			   #
# environment. Copy this file, rename it to 'build.properties' and define the  #
# following parameters.														   #
################################################################################

# Path to the keystore file for code signing
signing.keystore.path = %USERPROFILE%/ci.p12
# Alias of the key in the keystore for code signing
signing.key.alias     = ci

# Path to .NET Core installation
dotnetcore.path       = %ProgramFiles%/dotnet
# Path to PHP installation
php.path              = /usr/bin/php
# Path to Python installation
python.path           = /usr/bin/python
